apiVersion: apps/v1
kind: Deployment
metadata:
  name: medai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medai
  template:
    metadata:
      labels:
        app: medai
    spec:
      containers:
      - name: medai-app
        image: ardamamurtum/medai-app:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: medai-service
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30003
  selector:
    app: medai
