name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t medai-app .

    - name: Download production DICE score
      uses: actions/download-artifact@v2
      with:
        name: prod_dice_score
        path: .

    - name: Run unit tests
      run: pytest
